product1_code, product1_unit, product1_price = input().split()
product2_code, product2_unit, product2_price = input().split()
product1_code = int(product1_code)
product1_price = float(product1_price)
product1_unit = int(product1_unit)
product2_code = int(product2_code)
product2_price = float(product2_price)
product2_unit = int(product2_unit)
product1_sum =float(product1_unit*product1_price)
product2_sum =float(product2_unit*product2_price)
totalPrice=float(product1_sum+product2_sum)
print("VALOR A PAGAR: R$ "+ "{0:.2f}".format(totalPrice))
